version: '3'
services:
  backend:
    container_name: gestor_backend
    build: ./backend
    ports:
      - "4000:4000"
    networks:
      - red-libros

  frontend:
    build: ./frontend
    ports:
      - "80:80"
    networks:
      - red-libros

  jenkins:
    build:
      context: ./jenkins-custom
      dockerfile: Dockerfile
    container_name: gestor-libros-jenkins
    ports:
      - "8080:8080"
    volumes:
      - jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    user: root
    networks:
      - red-libros

networks:
  red-libros:

volumes:
  jenkins_home: