name: CI Gestor Libros

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Clonar repo
        uses: actions/checkout@v2

      - name: Instalar Docker Compose
        run: |
          sudo apt-get update
          sudo apt-get install -y docker-compose

      - name: Construir contenedores Docker
        run: docker-compose build

      - name: Levantar contenedores
        run: docker-compose up -d

      - name: Esperar que backend esté activo
        run: sleep 5

      - name: Ejecutar prueba de backend
        run: docker-compose exec -T backend npm test